---

- include_tasks: el_prep.yml
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- include_tasks: el_install.yml
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- include_tasks: deb_prep.yml
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- include_tasks: deb_install.yml
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Copy Docker engine service file
  register: change_docker
  template:
    src: "docker.service.j2"
    dest: "{{ systemd_dir }}/docker.service"
    owner: root
    group: root
    mode: 0755

- name: Copy Docker environment config file
  template: src=docker.j2 dest={{ system_env_dir }}/docker
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: Add any insecure registries to Docker config
  when:
    - insecure_registries is defined and insecure_registries | length > 0
    - ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
  lineinfile: dest={{ system_env_dir }}/docker regexp=^INSECURE_REGISTRY= line=INSECURE_REGISTRY="{% for reg in insecure_registries %}--insecure-registry={{ reg }} {% endfor %}"

- name: Add registry to Docker config
  when: 
    - add_registry is defined and add_registry > 0
    - ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
  lineinfile: dest={{ system_env_dir }}/docker regexp=^ADD_REGISTRY= line=ADD_REGISTRY="{% for reg in add_registry %}--add-registry={{ reg }} {%endfor %}"

- name: Enable and check Docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_docker
